### ISSUE TITLE
Alpine instead of ubuntu

### ISSUE THREAD

**Issue by enahum** [mattermost/mattermost-docker#10]
I believe since Docker official images are moving to alpine instead of ubuntu basically cause the alpine image is a lot smaller than ubuntu we should consider to do the same thing.

What are your thoughts on this?

**Comment by npcode** [comment]
The reason I am using Ubuntu is because mattermost provides [the install guide](https://github.com/mattermost/docs/blob/master/source/install/prod-ubuntu.rst), which makes it easy to build and maintain the docker image. For example, [I just linked the document in my README.md](https://github.com/mattermost/mattermost-docker/blob/master/README.md#more-informations) to save my time. :)

I agree with you that smaller is better but I'm not yet sure whether it is important enough.

**Comment by enahum** [comment]
@npcode that being said then if we write an install guide for alpine you would consider moving the image to use alpine? this is only thinking about smaller containers, nothing else really

**Comment by npcode** [comment]
@enahum Sure!

**Comment by enahum** [comment]
Ok then next steps are:

1. Write an install guide for alpine linux
2. Move docker images to use alpine linux

anything else comes to mind?

**Comment by npcode** [comment]
@enahum It seems to be enough. Thanks!

**Comment by auguster** [comment]
I just had some fun converting the Dockerfile of app to Alpine, the image's size shrunk from 298.5 MB to 90.41 MB. It's really worth it :)

**Comment by esethna** [comment]
If anyone from the community is interested in writing an install guide for alpine linux, please feel free to submit a PR to the [docs repo](https://github.com/mattermost/docs/tree/master/source/install). Thanks!
