### ISSUE TITLE
Support for docker Stack

### ISSUE THREAD

**Issue by thepill** [mattermost/mattermost-docker#104]
Would be great if you could supply Support/documentation for the docker stack mode.

Thanks!

**Comment by xcompass** [comment]
Never played with docker stack. Would you be willing to submit a PR?

**Comment by pichouk** [comment]
@pastukhov in #147 seems to say that using a docker-compose version 3 file should made I work with Docker Stack.
Since it seems that there is no breaking changes for us on docker-compose v3 ([see changes](https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading)), I think we could move on this version.

**Comment by pichouk** [comment]
Just opened a PR for this. But seems that dcoker-compose v3 required a "high" version of Docker Engine, not already supported on all distributions.

**Comment by pichouk** [comment]
PR #176 introduced swarm mode support !
