### ISSUE TITLE
Help With Setup

### ISSUE THREAD

**Issue by linuxorbust** [mattermost/mattermost-docker#14]
Thanks so much for creating this.  I'm currently just trying to set this up on a Mac so I can see if it would be feasible in production.  I'm fairly new to both docker and mattermost so I could really use some help.  I'm not sure where to go to edit the listen address that mattermost is using for others to connect to.

For example in the one line install I was able to change my host file and point to dockerhost:8065.  The only thing I'm finding here is something about 80:80 and that we shouldn't modify the listen address in the service settings.  

Sorry for my ignorance.  Am I to assume that the docker IP is the one that's being used?  If so, I'm getting a failed to connect error.  How can I change the settings and then how would I go about verifying that the service is running?  I've tried putting in the IP, adding to my host file etc and still can't reach the mattermost build from the same Mac.

Any help would be appreciated.

**Comment by npcode** [comment]
> For example in the one line install I was able to change my host file and point to dockerhost:8065. The only thing I'm finding here is something about 80:80 and that we shouldn't modify the listen address in the service settings.

You can change the listen port by modifying the "80:80". For example, if you want that your mattermost instance listens 8080 instead of 80, modify it to "8080:80". See "ports" section at https://docs.docker.com/compose/compose-file/ for more details.

> Am I to assume that the docker IP is the one that's being used?

It's true only if you "restart", not "recreate", the container. `docker-compose restart` is okay but `docker-compose rm && docker-compose run` may be not okay.

Note: We have a permission issue on installation on osx. See #6.

**Comment by linuxorbust** [comment]
So it sounds like if I'm opting for nossl, then I would just edit the docker-compose-nossl.yml file and change the 80:80 to 8080:80 or whatever ports I want to use.  What I'm not seeing is if there's any way to verify or determine what IP mattermost is using.  

When I restart using docker-compose restart, I can see that the db and app is running so I know I've come that far.  I'm probably just over thinking things.  Connecting to the one line install was a breeze, but for some reason this has been difficult.

**Comment by npcode** [comment]
> If not, then what is the IP?

Well, let me make it clear. The IP of the docker container changes when you recreate the container. But you can access your mattermost instance without worrying about it because docker binds the ip and the port to your host.

For example, you can see the port binding when you run `docker ps` as follows:

```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                            NAMES
c59b85bf96e5        mattermostdocker_app   "/bin/sh -c /docker-e"   2 seconds ago       Up 1 seconds        0.0.0.0:80->80/tcp               mattermostdocker_app_1
78e87818d92b        mattermostdocker_db    "/docker-entrypoint1."   8 days ago          Up 2 seconds        5432/tcp                         mattermostdocker_db_1
```

`0.0.0.0:80->80/tcp` means the port 80 of the docker container is bound to the port of your host. You can just open `http://<your-host-ip>` with your web browser to access your mattermost instance. (I guess you already know your host ip)

**Comment by linuxorbust** [comment]
Ah looks like I may have found the problem.  When I run docker ps it only has mattermostdockermaster_app listed.  Though when I run docker-compose start it shows both the app and db starting.
