### ISSUE TITLE
Environment variable disables Email Notifications config option

### ISSUE THREAD

**Issue by adngdb** [mattermost/mattermost-docker#140]
This change https://github.com/mattermost/mattermost-docker/commit/6512a09608c5a3566aa973c9359451d37023ea61#diff-7bfa124914e2e8affd23055295839cb8R14 seems to have broken the Enable Email Notifications config option. Whatever the value is in the ``config.json`` file, it always shows ``false`` in the System console, and the warning at the top is always showing as well. See this problem in the forum for example: https://forum.mattermost.org/t/email-notification-settings-dont-stick/3386/5

My proposed solution is: add ``- MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS=true`` to the environment namespace of the ``app`` service in your ``docker-compose.yml`` file, and re-run the service.

However, that is very unintuitive, especially seems the expected behavior is that changing the option in the System console should just work.

**Comment by pichouk** [comment]
Using environment variables not worked (as you wan see) so this issue was fixed by https://github.com/mattermost/mattermost-docker/commit/87b26e155e1242972fad8d31381089631510e3dc.
It should work now, I test this locally and in production (I don't understand why one of the Travis test have a git error). So `master` should work, could you try to reproduce [here](https://forum.mattermost.org/t/email-notification-settings-dont-stick/3386/5) but using the `master` branch ?

**Comment by xdgc** [comment]
lgtm

**Comment by adngdb** [comment]
Hah, OK, so this was bad luck for me. I cloned the repo right before you landed your fix (and obviously used ``master`` instead of a tag). Sorry for the noise! :)
