### ISSUE TITLE
Docker Hub image for app includes team edition

### ISSUE THREAD

**Issue by makeacode** [mattermost/mattermost-docker#158]
The 4.0.1 app image on docker hub points to team edition instead of enterprise...please fix.

**Comment by makeacode** [comment]
The 3.9.0 image for app also says it's team edition.

**Comment by pichouk** [comment]
@jasonblais I have no access to the Docker integration part. I think only `mattermost` organization members or repository owners could fix this. Also I think it need an access to `mattermost` organization on Docker Hub I guess.

According to me, the problem is that Docker Hub use the wrong Dockerfile, I don't know why.

**Comment by makeacode** [comment]
I noticed the default Dockerfile installs the team edition...perhaps it could be switched so it installs enterprise by default.

**Comment by pichouk** [comment]
I don't know if it is the expected behavior or not. According to me it seems logic to build the Team edition by default.
We also discuss of this on https://github.com/mattermost/mattermost-docker/pull/146

**Comment by makeacode** [comment]
I would agree that it's more logical to build and ship the "free" version but all the documentation on docker hub states that it's the enterprise edition

**Comment by pichouk** [comment]
That's a good point 👍

**Comment by pichouk** [comment]
Up @jasonblais

**Comment by pichouk** [comment]
After some checks, it seems that current Docker Hub image correctly provide an Enterprise Edition Mattermost.

As discussed on PR https://github.com/mattermost/mattermost-docker/pull/146 and on [Mattermost Developpers channel](https://pre-release.mattermost.com/core/pl/mx7q35cdc7bd5fgkeuqhmgunry) you can use Enterprise Edition image without license, the behavior will be the same as a Team Edition (instead of a little other tab on Console System).
