### ISSUE TITLE
 [details: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-1']

### ISSUE THREAD

**Issue by cobenash** [mattermost/mattermost-docker#168]
its seems that the env "AWS_REGION" is not working at 4.1 

I saw there was a issue [Mattermost does not read the AWS S3 region setting](https://github.com/mattermost/platform/issues/6999) which is similar with the situation I encounted.

How can I fix that ? All the images are gone right now at our mattermost platform

**Comment by pichouk** [comment]
I don't understand, is this an issue with `mattermost/platform` ? Seems it is not Docker related.

**Comment by cobenash** [comment]
@pichouk  Thanks for your quick reply.  It doesn't work even we change the env variable "AWS_REGION" at the docker-compose.yml. Is it the Platform problems?

**Comment by pichouk** [comment]
If you correctly set the env variable on your docker-compose file, I think there is no reason that the problem is on the Docker part. I think you should see on `mattermost/platform` repository if they have any information about this.  
If it turns out that it work correctly for non-Docker deployment, we will see on our side.

**Comment by cobenash** [comment]
OK Thanks. I see.
