### ISSUE TITLE
Push Team edition on Docker Hub

### ISSUE THREAD

**Issue by yukiisbored** [mattermost/mattermost-docker#202]
Building an image is a bit of a pain especially when you have limited bandwidth. I suggest pushing a version with the team edition to the docker hub instead of just the enterprise edition.

**Comment by pichouk** [comment]
We discussed about this on (merged) PR#146. Because we maintain only one Dockerfile we only have auto-build on Docker Hub for Enterprise Edition.

But [someone from Mattermost staff](https://pre-release.mattermost.com/core/pl/iu3tcchfifnz3mgwctdpf9zd8a) explained that you can use Enterprise Edition images (from Docker Hub) even if you have no license. Then it will be **exactly** the same as Team Edition. So even if you don't want to build Team Edition by yourself you can use Docker Hub images :)
