### ISSUE TITLE
the https://hub.docker.com/r/mattermost/platform/ image is gone !

### ISSUE THREAD

**Issue by rdubigny** [mattermost/mattermost-docker#25]
Hi,

We are using this image for our production environment.

Can you restore it please ? Or maybe this image should not be used in production ?

**Comment by crspeller** [comment]
It isn't recommended for production. The new location for the preview image is here: https://hub.docker.com/r/mattermost/mattermost-preview/

**Comment by it33** [comment]
Hi @rdubigny, yes, the name of the image was confusing so it's been replaced by https://hub.docker.com/r/mattermost/mattermost-preview/ since that single-machine Docker images is designed for previewing Mattermost. 

There's [a new multi-node production setup for Docker](http://docs.mattermost.com/install/prod-docker.html) that would be recommended for production. 

Links at http://www.mattermost.org/download/ are updated, so anyone installing for the first time should get to the right place.

**Comment by it33** [comment]
@rdubigny just curious, how did you notice this so quickly?

**Comment by rdubigny** [comment]
@it33 we were reading the dockerfile at this URL when you did the change. The page suddenly returned a 404 error ;)

thx for the quick answer !

**Comment by rdubigny** [comment]
@it33 I don't feel safe with your new images not being tagged on docker hub. Can you tag them ?

**Comment by crspeller** [comment]
@rdubigny There should be a 3.0 tag now.

**Comment by rdubigny** [comment]
@crspeller don't want to bother you but only the preview is tagged, not the app nor the db.
