### ISSUE TITLE
Add missing config to config.json

### ISSUE THREAD

**Issue by pgold30** [mattermost/mattermost-docker#302]
I see that the configmap is missing some config like 
https://docs.mattermost.com/administration/config-settings.html 

 "EnableEmojiPicker": true,
 "EnableGifPicker": false
 and others 

https://docs.mattermost.com/administration/config-settings.html

**Comment by pichouk** [comment]
Yes it is. In fact we do not always update the config template everytime it changes because we don't need to. At startup, Mattermost application will populate the file with missing fields.

If you want to add some fields (especially if you think we should change one of the default values) to the configuration template, feel free to submit a PR :)

**Comment by pgold30** [comment]
https://github.com/mattermost/mattermost-kubernetes/pull/52 this was related to mattermost-kubernetes  i got confused, anyway i did the PR :)
