### ISSUE TITLE
Release 5.1.2

### ISSUE THREAD

**Issue by liepertt** [mattermost/mattermost-docker#311]
The Release 5.1.2 with an urgent security fix is missing.

**Comment by pichouk** [comment]
You can upgrade to `5.2.2` or `5.3.1` instead.

**Comment by liepertt** [comment]
As this is our production server I plan to upgrade I would like just a minor fix upgrade. And do further Tests on our staging server before moving our production server to another feature update.

**Comment by pichouk** [comment]
Seems legit.

I am not able to push images to Docker Hub. Maybe @jasonblais or @cpanato are able to build and push an image for `5.1.2` (just need to change the `app/Dockerfile`)

**Comment by cpanato** [comment]
@pichouk i can build and push

**Comment by cpanato** [comment]
@pichouk @liepertt image is available https://hub.docker.com/r/mattermost/mattermost-prod-app/tags/

**Comment by jasonblais** [comment]
Do we need to update anything in our build process for future? Curious why 5.2.2 was pushed to Docker Hub but not 5.1.2.

@cpanato @pichouk

**Comment by cpanato** [comment]
the tag 5.1.2 was not created, i guess

**Comment by jasonblais** [comment]
Right, but do we know why? May that happen in the future?

**Comment by cpanato** [comment]
no sure. @pichouk any thoughts?

**Comment by pichouk** [comment]
(Sorry for the delay). I think I know what happen. 

`5.1.2` was released the same day (2018, September 16th) than `5.2.0` so we upgraded the image without noticing that the `5.1.2` version was missing. In fact when a new minor (eg. `5.2.X`) version is released, we do not maintain the previous one if there is a patch version (eg. `5.1.Y`).

We should be better at maintaining some Git branches for previous versions in order to easily continue to upgrade patch versions. IMHO @liepertt use case is legit.
