### ISSUE TITLE
Mattermost docker creating volume for plugins

### ISSUE THREAD

**Issue by gotjoshua** [mattermost/mattermost-docker#356]
I have abasically standard suggested docker-compose with labels for traefik and DB_HOST: local-postgres-container.
This line is in the volumes section of my docker-compose:
`- ./volumes/app/mattermost/plugins:/mattermost/plugins:rw`

i notice in portainer that the mm-app is creating a volume and mounting it into:
/mattermost/client/plugins
![mm-app_2pluginfolders](https://user-images.githubusercontent.com/8686454/50897783-1880d880-1405-11e9-8f92-e2492f6f41ec.png)
Where is this being created and mounted? (not in my docker-compose)?

i prefer to avoid local volumes (and keep the mounted folders relative to the docker-compose file)
should i change the line above to:
`- ./volumes/app/mattermost/plugins:/mattermost/client/plugins:rw`

?

**Comment by pichouk** [comment]
The `/mattermost/client/plugins` folder is declared as a volume on the [`app` Dockerfile](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile#L53), this is why a volume is created. It was introduced in [this PR](https://github.com/mattermost/mattermost-docker/pull/312) but you can also add another line (like the one you suggested) inside the Docker Compose (but do not replace the existing one for `/mattermost/plugins`).

Feel free to submit a PR for this, I'll do it otherwise.

**Comment by gotjoshua** [comment]
great! feels more consistent. Cheers!
