### ISSUE TITLE
Big pg_xlog folder

### ISSUE THREAD

**Issue by cobenash** [mattermost/mattermost-docker#73]
After I use this images and built the container with docker compose, I found out that there are big folder called pg_xlog.

How can I delete that and keep the folder size small forever ?

**Comment by xcompass** [comment]
Did you enable S3 backup? If yes and for some reason, postgres can't send those backups to S3, the pg_xlog will filled up with pending files. 

If you don't use S3 backup, you can disable it so that postgres won't try to store those in pg_xlog.

If you use S3, you need to check if there is anything wrong with your setup (key, secret, bucket) to prevent those files being sent out.

**Comment by cobenash** [comment]
@xcompass thanks, I already fix the problems. 👍

**Comment by xcompass** [comment]
Great. Sorry for the delay
